sheet_id = "1v-xhNO9b91mwZqnAEsNtaXSnnb10u0IpPOoMxOj4Tic"
OPENAI_API_KEY = "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"
usage_sheet_id = "183OydTXwzGiXmB0Im19CDpI6kUXpE6qRKaJ45mAuAKI"
feedback_sheet_id = "1S5OWhkZcHrN941Yr0y8QFutEz9NfwccPcqDgfAaq9yI"
